import * as csTools from '@cornerstonejs/tools';

import { eventTarget } from '@cornerstonejs/core';
import { setUpNhicAnnotationBridge } from './setUpNhicAnnotationBridge';

const { Enums: csToolsEnums } = csTools;

const _autoAcceptAnnotationInterpolationHandler = evt => {
  const { element } = evt.detail;
  csTools.utilities.contours.acceptAutogeneratedInterpolations(element, {});
};

export const setUpAnnotationEventHandlers = (): [() => void, () => void] => {
  eventTarget.addEventListener(
    csToolsEnums.Events.ANNOTATION_INTERPOLATION_PROCESS_COMPLETED,
    _autoAcceptAnnotationInterpolationHandler
  );

  const annotationInterpolationProcessCompletedUnsubscribe = () => {
    eventTarget.removeEventListener(
      csToolsEnums.Events.ANNOTATION_INTERPOLATION_PROCESS_COMPLETED,
      _autoAcceptAnnotationInterpolationHandler
    );
  };

  const nhicBridgeUnsubscribe = setUpNhicAnnotationBridge();

  return [annotationInterpolationProcessCompletedUnsubscribe, nhicBridgeUnsubscribe];
};
